"""empty message

Revision ID: 9fe234ba9a0d
Revises: 
Create Date: 2023-03-05 15:00:40.532273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe234ba9a0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('habits', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('default_icon', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_icon')
    op.drop_column('habits', 'start_date')
    op.drop_table('icons')
    # ### end Alembic commands ###
